version: '3.8'

services:
  # Flask应用服务
  app:
    image: polarsnowleopard/ioeb-backend:latest
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_DEBUG=${FLASK_DEBUG:-0}
      - SECRET_KEY=${SECRET_KEY:-default_secret_key}
      - DB_USERNAME=${DB_USERNAME:-default_username}
      - DB_PASSWORD=${DB_PASSWORD:-default_password}
      - DB_HOST=${DB_HOST:-sh-cynosdbmysql-grp-gfzuhdpw.sql.tencentcdb.com}
      - DB_PORT=${DB_PORT:-22254}
      - DB_NAME=${DB_NAME:-ioeb-dev}

    volumes:
      - app_data:/app/uploads
      - app_db:/app/instance
  #   depends_on:
  #     - redis

  # # Redis缓存服务
  # redis:
  #   image: redis:alpine
  #   restart: always
  #   volumes:
  #     - redis_data:/data

  # # Nginx反向代理
  # nginx:
  #   image: nginx:alpine
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - ./nginx/ssl:/etc/nginx/ssl
  #     - ./static:/var/www/static
  #   depends_on:
  #     - app

volumes:
  app_data:
  app_db:
  redis_data:
