version: '3.8'

services:
  # Flask应用服务
  app:
    image: polarsnowleopard/ioeb-backend:latest
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1

    volumes:
      - app_data:/app/uploads
      - app_db:/app/instance
  #   depends_on:
  #     - redis

  # # Redis缓存服务
  # redis:
  #   image: redis:alpine
  #   restart: always
  #   volumes:
  #     - redis_data:/data

  # # Nginx反向代理
  # nginx:
  #   image: nginx:alpine
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - ./nginx/ssl:/etc/nginx/ssl
  #     - ./static:/var/www/static
  #   depends_on:
  #     - app

volumes:
  app_data:
  app_db:
  redis_data:
